#!/usr/bin/env bash
. colors.sh
[[ -n "$(git symbolic-ref HEAD 2> /dev/null)" ]] && {
	echo -e "${COLOR_BLUE}${COLOR_BOLD}BRANCHES:${COLOR_RESET}"
	git remote show | xargs -n1 git remote show
	echo -e "\n${COLOR_BLUE}${COLOR_BOLD}STATUS:${COLOR_RESET}"
	[[ -n "$(git status -s 2>/dev/null)" ]] &&
		git status -s || 
		echo "working directory is clean"
	echo -e "\n${COLOR_BLUE}${COLOR_BOLD}LOG:${COLOR_RESET}"
	git log -5 --oneline --color | cat
} || echo "Not a git repository" 1>&2
