#!/usr/bin/env bash

URL="http://browsers.garykeith.com/stream.asp?PHP_BrowsCapINI"

task_start "finding browscap directory"
PATH_BROWSCAP=`php -r 'echo ini_get("browscap");'`
[[ ! ${PATH_BROWSCAP} ]] && task_fail "php browscap path not set" || task_done

task_start "downloading (${URL})"
task_end $(curl -s -S "${URL}" -o "${PATH_BROWSCAP}")