#!/usr/bin/env bash

updateBundles() {
	[[ ! -d "$1" ]] && return 1
	for i in "$1"/*; do
		git_update "$i"
	done
}

updateBundles "/Library/Application Support/TextMate/Bundles"
updateBundles ~/"Library/Application Support/TextMate/Pristine Copy/Bundles"