#!/usr/bin/env bash

download_dir="$TMPDIR/webkit-nightly"

on_fail() {
	hdiutil detach -quiet /Volumes/WebKit
	[[ -e "$download_dir" ]] && rm -rf $download_dir
}

task_start "checking for existing installation"
app_path="`find_app "org.webkit.nightly.WebKit"`"
if [[ $? != 0 ]]; then
	install_dir="/Applications"
	task_skip "Not found"
else
	install_dir="`dirname "$app_path"`"
	task_done "$install_dir"
fi

task_start "finding latest build"
URL=$(curl --max-time 10 -s -S http://nightly.webkit.org/ | grep dmg | head -1 | perl -pe 's/.*(http.*dmg).*/$1/')
FILE=$(basename "$URL")
task_end

task_start "downloading"
mkdir -p $download_dir && cd $download_dir
curl -s -S $URL --remote-name
task_end

task_start "mounting"
hdiutil attach -quiet $download_dir/$FILE
task_end

task_start "installing into (${install_dir})"
if [[ -e $install_dir/WebKit.app ]]; then 
	mv $install_dir/WebKit.app ~/.Trash/WebKit-`date +%Y-%m-%d_%H-%M-%s`.app/ || task_fail "couldn't move old revision"
fi
cp -R "/Volumes/WebKit/WebKit.app" "$install_dir/"
task_end

task_start "cleaning up"
on_fail
task_end